"use server";

import { GoogleGenAI } from "@google/genai";

export async function generateDesign(formData: FormData, clientApiKey?: string) {
  try {
    const apiKey = clientApiKey || process.env.GEMINI_API_KEY || process.env.NEXT_PUBLIC_GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("API Key configuration missing");
    }

    const ai = new GoogleGenAI({ apiKey });

    const file = formData.get("image") as File;
    const promptText = formData.get("prompt") as string;

    if (!file || !promptText) {
      throw new Error("Missing image or prompt");
    }

    const arrayBuffer = await file.arrayBuffer();
    const base64Image = Buffer.from(arrayBuffer).toString("base64");

    const prompt = [
      { text: promptText },
      {
        inlineData: {
          mimeType: file.type || "image/png",
          data: base64Image,
        },
      },
    ];

    const response = await ai.models.generateContent({
      model: "gemini-2.0-flash-exp",
      contents: prompt,
    });

    const candidates = response.candidates;
    if (!candidates || candidates.length === 0) {
      throw new Error("No candidates returned from Gemini");
    }

    const parts = candidates[0].content?.parts;
    if (!parts) {
      throw new Error("No generated content parts found");
    }

    for (const part of parts) {
       if (part.inlineData) {
         return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
       }
    }
    
    throw new Error("No image generated by the AI");

  } catch (error: any) {
    console.error("Gemini Generation Error:", error);
    
    // Check for quota/rate limit errors
    if (error.code === 429 || error.status === "RESOURCE_EXHAUSTED") {
      throw new Error("Quota exceeded for this model. Please try again later or check your API plan.");
    }

    throw new Error(error.message || "Failed to generate design");
  }
}
